"""
Runtime bridge for LIS/GMAO-style SAC-SMA prognostic-state perturbations.

Execution order intentionally follows NASA LIS:

    model advance
       ->
    prognostic-state perturbation
       ->
    data assimilation

At the NGIAB sidecar boundary the native SAC-SMA model has already advanced.
Therefore this bridge perturbs only catchment_states in the synchronized
post-model request.

The current-step SAC-SMA qlat/tci values are deliberately NOT recomputed or
perturbed.  They were generated by the model advance that precedes the LIS
state-perturbation boundary.

Modes
-----
off
    Bitwise behavioral equivalent of V20.

capture
    Do not perturb states.  Collect normalized six-state ensemble covariance
    statistics for specification of the LIS cross-variable correlation matrix.

perturb
    Apply the validated LIS/GMAO perturbation kernel every synchronized model
    step, then provide those states to the PF and/or native member writeback.
"""

from __future__ import annotations

import copy
import json
import math
import os
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np

from ngiab_da.integration.sacsma_lis_gmao_state_perturbation import (
    LISGMAOStatePerturbationConfig,
    LISGMAOStatePerturber,
    SACSMA_STATE_NAMES,
    lis_sqrt_correlation_matrix,
)


_MODE_ENV = "NGIAB_DA_SACSMA_LIS_GMAO_MODE"
_CONFIG_ENV = "NGIAB_DA_SACSMA_LIS_GMAO_CONFIG"
_CONFIG_JSON_ENV = "NGIAB_DA_SACSMA_LIS_GMAO_CONFIG_JSON"

_VALID_MODES = {
    "off",
    "capture",
    "perturb",
}


class SACSMALISGMAORuntimeError(RuntimeError):
    pass


class _RunningMoments:
    """Exact online first/second moments of six-dimensional samples."""

    def __init__(self) -> None:
        self.count = 0
        self.total = np.zeros(6, dtype=np.float64)
        self.cross = np.zeros((6, 6), dtype=np.float64)

    def update(self, rows: np.ndarray) -> None:

        array = np.asarray(rows, dtype=np.float64)

        if array.ndim != 2 or array.shape[1] != 6:
            raise SACSMALISGMAORuntimeError(
                f"moment rows must have shape (n,6); got {array.shape}"
            )

        if not np.all(np.isfinite(array)):
            raise SACSMALISGMAORuntimeError(
                "moment rows contain nonfinite values"
            )

        self.count += int(array.shape[0])
        self.total += np.sum(array, axis=0)
        self.cross += array.T @ array

    def covariance(self) -> np.ndarray | None:

        if self.count < 2:
            return None

        n = float(self.count)

        return (
            self.cross
            - np.outer(self.total, self.total) / n
        ) / (n - 1.0)

    def correlation(self) -> np.ndarray | None:

        covariance = self.covariance()

        if covariance is None:
            return None

        variance = np.diag(covariance)

        if np.any(variance <= 0.0):
            return None

        scale = np.sqrt(variance)

        correlation = covariance / np.outer(scale, scale)

        correlation = 0.5 * (
            correlation
            + correlation.T
        )

        np.fill_diagonal(correlation, 1.0)

        return correlation


def _atomic_json(
    path: Path,
    payload: Mapping[str, Any],
) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = path.with_name(
        path.name + ".tmp"
    )

    temporary.write_text(
        json.dumps(
            payload,
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
        + "\n",
        encoding="utf-8",
    )

    temporary.replace(path)


def _parse_sacsma_parameter_file(
    path: Path,
) -> dict[str, float]:

    result: dict[str, float] = {}

    for line in path.read_text(
        encoding="utf-8"
    ).splitlines():

        stripped = line.strip()

        if (
            not stripped
            or stripped.startswith("#")
        ):
            continue

        parts = stripped.split()

        if len(parts) < 2:
            continue

        key = parts[0].lower()

        if key not in {
            "uztwm",
            "uzfwm",
            "lztwm",
            "lzfsm",
            "lzfpm",
        }:
            continue

        result[key] = float(parts[1])

    required = {
        "uztwm",
        "uzfwm",
        "lztwm",
        "lzfsm",
        "lzfpm",
    }

    missing = required - set(result)

    if missing:
        raise SACSMALISGMAORuntimeError(
            f"{path} missing SAC-SMA parameters: {sorted(missing)}"
        )

    return result


def _discover_capacity_files(
    *,
    run_directory: Path,
    ensemble_root: Path,
) -> dict[str, Path]:

    result: dict[str, Path] = {}

    preferred = (
        run_directory
        / "config"
        / "cat_config"
        / "SAC-SMA",

        run_directory
        / "control-run"
        / "config"
        / "cat_config"
        / "SAC-SMA",

        ensemble_root
        / "member-000"
        / "config"
        / "cat_config"
        / "SAC-SMA",

        ensemble_root.parent
        / "control-run"
        / "config"
        / "cat_config"
        / "SAC-SMA",
    )

    for directory in preferred:

        if not directory.is_dir():
            continue

        for path in sorted(
            directory.glob("params-*.txt")
        ):

            catchment_id = path.stem[len("params-"):]

            result.setdefault(
                catchment_id,
                path,
            )

    if result:
        return result

    # Fail-safe fallback for an unfamiliar run-package layout.
    for search_root in (
        run_directory,
        ensemble_root,
    ):

        if not search_root.exists():
            continue

        for path in search_root.rglob(
            "params-*.txt"
        ):

            catchment_id = path.stem[len("params-"):]

            result.setdefault(
                catchment_id,
                path,
            )

    return result


class SACSMALISGMAORuntimeBridge:

    def __init__(
        self,
        *,
        run_directory: str | Path,
        ensemble_root: str | Path,
        output_root: str | Path,
        member_ids: Sequence[str],
        expected_catchment_ids: Sequence[str],
    ) -> None:

        mode = os.environ.get(
            _MODE_ENV,
            "off",
        ).strip().lower()

        if mode not in _VALID_MODES:
            raise SACSMALISGMAORuntimeError(
                f"{_MODE_ENV} must be one of "
                f"{sorted(_VALID_MODES)}; got {mode!r}"
            )

        self.mode = mode

        self.member_ids = tuple(
            str(value)
            for value in member_ids
        )

        self.expected_catchment_ids = tuple(
            str(value)
            for value in expected_catchment_ids
        )

        self.run_directory = (
            Path(run_directory)
            .expanduser()
            .resolve()
        )

        self.ensemble_root = (
            Path(ensemble_root)
            .expanduser()
            .resolve()
        )

        self.output_root = (
            Path(output_root)
            .expanduser()
            .resolve()
            / "sacsma-lis-gmao"
        )

        self.output_root.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.capture_path = (
            self.output_root
            / "cross_variable_capture.json"
        )

        self.audit_path = (
            self.output_root
            / "perturbation_audit.jsonl"
        )

        self.restart_path = (
            self.output_root
            / "perturbation_restart.json"
        )

        self._parameter_files: dict[str, Path] = {}

        self._capacity_parameters: dict[
            str,
            dict[str, float],
        ] = {}

        self._perturber: (
            LISGMAOStatePerturber
            | None
        ) = None

        self._perturb_config: (
            LISGMAOStatePerturbationConfig
            | None
        ) = None

        self._std_fraction: np.ndarray | None = None

        self._random_seed: int | None = None

        self._previous_normalized: (
            np.ndarray
            | None
        ) = None

        self._state_anomaly = _RunningMoments()
        self._increment_anomaly = _RunningMoments()

        self._cycle_count = 0

        if self.mode != "off":

            self._parameter_files = (
                _discover_capacity_files(
                    run_directory=self.run_directory,
                    ensemble_root=self.ensemble_root,
                )
            )

            if not self._parameter_files:
                raise SACSMALISGMAORuntimeError(
                    "No SAC-SMA parameter files were discovered."
                )

        if self.mode == "perturb":
            self._load_perturb_config()


    @property
    def enabled(self) -> bool:
        return self.mode != "off"


    def _load_perturb_config(self) -> None:

        raw_json = os.environ.get(
            _CONFIG_JSON_ENV,
            "",
        ).strip()

        raw_path = os.environ.get(
            _CONFIG_ENV,
            "",
        ).strip()

        if raw_json:
            payload = json.loads(
                raw_json
            )

        elif raw_path:
            path = Path(
                raw_path
            ).expanduser().resolve()

            payload = json.loads(
                path.read_text(
                    encoding="utf-8"
                )
            )

        else:
            raise SACSMALISGMAORuntimeError(
                "Perturb mode requires either "
                f"{_CONFIG_JSON_ENV} or {_CONFIG_ENV}."
            )

        correlation = payload.get(
            "correlation_matrix"
        )

        if (
            not isinstance(correlation, list)
            or len(correlation) != 6
        ):
            raise SACSMALISGMAORuntimeError(
                "Production perturbation requires a frozen numeric "
                "6x6 correlation_matrix."
            )

        matrix = np.asarray(
            correlation,
            dtype=np.float64,
        )

        if matrix.shape != (6, 6):
            raise SACSMALISGMAORuntimeError(
                "correlation_matrix must be exactly 6x6."
            )

        # Fail closed exactly as the validated kernel does.
        lis_sqrt_correlation_matrix(
            matrix
        )

        tcorr = payload.get(
            "temporal_correlation_seconds"
        )

        if (
            not isinstance(tcorr, list)
            or len(tcorr) != 6
        ):
            raise SACSMALISGMAORuntimeError(
                "temporal_correlation_seconds must contain six values."
            )

        std_fraction = payload.get(
            "initial_std_fraction_of_capacity"
        )

        if (
            not isinstance(std_fraction, list)
            or len(std_fraction) != 6
        ):
            raise SACSMALISGMAORuntimeError(
                "initial_std_fraction_of_capacity must contain six values."
            )

        std_fraction_array = np.asarray(
            std_fraction,
            dtype=np.float64,
        )

        if (
            not np.all(
                np.isfinite(
                    std_fraction_array
                )
            )
            or np.any(
                std_fraction_array < 0.0
            )
        ):
            raise SACSMALISGMAORuntimeError(
                "state perturbation SD fractions must be finite "
                "and nonnegative."
            )

        frequency = float(
            payload.get(
                "frequency_seconds",
                3600.0,
            )
        )

        if not math.isclose(
            frequency,
            3600.0,
            rel_tol=0.0,
            abs_tol=1.0e-12,
        ):
            raise SACSMALISGMAORuntimeError(
                "Initial V21 contract requires hourly state perturbation."
            )

        perturbation_type = str(
            payload.get(
                "perturbation_type",
                "",
            )
        ).lower()

        if perturbation_type != "additive":
            raise SACSMALISGMAORuntimeError(
                "Initial V21 contract requires additive perturbations."
            )

        self._perturb_config = (
            LISGMAOStatePerturbationConfig(
                std_normal_max=float(
                    payload[
                        "std_normal_max"
                    ]
                ),
                temporal_correlation_seconds=tuple(
                    float(value)
                    for value in tcorr
                ),
                zero_mean=bool(
                    payload[
                        "zero_mean"
                    ]
                ),
                correlation=tuple(
                    tuple(
                        float(value)
                        for value in row
                    )
                    for row in matrix
                ),
            )
        )

        self._std_fraction = (
            std_fraction_array
        )

        self._random_seed = int(
            payload[
                "perturbation_random_seed"
            ]
        )


    def _capacity_for(
        self,
        catchment_id: str,
    ) -> dict[str, float]:

        catchment_id = str(
            catchment_id
        )

        existing = (
            self._capacity_parameters
            .get(
                catchment_id
            )
        )

        if existing is not None:
            return existing

        path = self._parameter_files.get(
            catchment_id
        )

        if path is None:
            raise SACSMALISGMAORuntimeError(
                "No SAC-SMA parameter file for "
                f"{catchment_id!r}."
            )

        parsed = (
            _parse_sacsma_parameter_file(
                path
            )
        )

        self._capacity_parameters[
            catchment_id
        ] = parsed

        return parsed


    def _extract(
        self,
        requests: Sequence[
            Mapping[str, Any]
        ],
    ) -> tuple[
        np.ndarray,
        tuple[tuple[str, int], ...],
        np.ndarray,
    ]:

        if len(requests) != len(
            self.member_ids
        ):
            raise SACSMALISGMAORuntimeError(
                "request/member count differs."
            )

        schema: (
            tuple[tuple[str, int], ...]
            | None
        ) = None

        member_arrays: list[
            np.ndarray
        ] = []

        for expected_member, request in zip(
            self.member_ids,
            requests,
        ):

            if str(
                request.get(
                    "member_id",
                    "",
                )
            ) != expected_member:
                raise SACSMALISGMAORuntimeError(
                    "request member ordering differs."
                )

            raw_states = request.get(
                "catchment_states"
            )

            if (
                not isinstance(
                    raw_states,
                    Sequence,
                )
                or isinstance(
                    raw_states,
                    (str, bytes),
                )
                or not raw_states
            ):
                raise SACSMALISGMAORuntimeError(
                    "catchment_states missing."
                )

            current_schema = tuple(
                (
                    str(raw["catchment_id"]),
                    int(raw["module_index"]),
                )
                for raw in raw_states
            )

            if schema is None:
                schema = current_schema
            elif schema != current_schema:
                raise SACSMALISGMAORuntimeError(
                    "SAC-SMA state schema differs by member."
                )

            matrix = np.asarray(
                [
                    [
                        float(raw[name])
                        for name in (
                            SACSMA_STATE_NAMES
                        )
                    ]
                    for raw in raw_states
                ],
                dtype=np.float64,
            )

            if (
                matrix.shape
                != (
                    len(raw_states),
                    6,
                )
                or not np.all(
                    np.isfinite(
                        matrix
                    )
                )
            ):
                raise SACSMALISGMAORuntimeError(
                    "invalid SAC-SMA state payload."
                )

            member_arrays.append(
                matrix
            )

        assert schema is not None

        # Member, catchment, state
        mcs = np.stack(
            member_arrays,
            axis=0,
        )

        # State, catchment, member
        scm = np.transpose(
            mcs,
            (2, 1, 0),
        )

        upper = np.empty(
            (
                6,
                len(schema),
            ),
            dtype=np.float64,
        )

        for index, (
            catchment_id,
            _module_index,
        ) in enumerate(schema):

            params = self._capacity_for(
                catchment_id
            )

            upper[:, index] = (
                params["uztwm"],
                params["uzfwm"],
                params["lztwm"],
                params["lzfsm"],
                params["lzfpm"],
                (
                    params["uztwm"]
                    + params["lztwm"]
                ),
            )

        if np.any(upper <= 0.0):
            raise SACSMALISGMAORuntimeError(
                "SAC-SMA capacities must be positive."
            )

        return (
            scm,
            schema,
            upper,
        )


    @staticmethod
    def _rows_from_anomalies(
        array: np.ndarray,
    ) -> np.ndarray:

        # Input: state, catchment, member
        anomalies = (
            array
            - np.mean(
                array,
                axis=2,
                keepdims=True,
            )
        )

        # Rows: catchment/member samples; columns: six states.
        return (
            np.transpose(
                anomalies,
                (1, 2, 0),
            )
            .reshape(
                -1,
                6,
            )
        )


    def _capture(
        self,
        *,
        state: np.ndarray,
        upper: np.ndarray,
        schema: tuple[
            tuple[str, int],
            ...
        ],
        cycle_index: int,
        analysis_epoch_seconds: int,
    ) -> None:

        normalized = (
            state
            / upper[:, :, None]
        )

        self._state_anomaly.update(
            self._rows_from_anomalies(
                normalized
            )
        )

        if (
            self._previous_normalized
            is not None
        ):

            increment = (
                normalized
                - self._previous_normalized
            )

            self._increment_anomaly.update(
                self._rows_from_anomalies(
                    increment
                )
            )

        self._previous_normalized = (
            np.array(
                normalized,
                copy=True,
            )
        )

        state_corr = (
            self._state_anomaly
            .correlation()
        )

        increment_corr = (
            self._increment_anomaly
            .correlation()
        )

        def matrix_payload(
            matrix: np.ndarray | None,
        ):

            if matrix is None:
                return None

            return [
                [
                    float(value)
                    for value in row
                ]
                for row in matrix
            ]

        def min_eigenvalue(
            matrix: np.ndarray | None,
        ):

            if matrix is None:
                return None

            return float(
                np.min(
                    np.linalg.eigvalsh(
                        matrix
                    )
                )
            )

        payload = {
            "schema_version": 1,
            "method":
                "normalized-SAC-SMA-ensemble-capture",
            "state_order":
                list(
                    SACSMA_STATE_NAMES
                ),
            "cycle_count":
                self._cycle_count,
            "latest_cycle_index":
                int(cycle_index),
            "latest_analysis_epoch_seconds":
                int(
                    analysis_epoch_seconds
                ),
            "catchment_count":
                len(schema),
            "member_count":
                len(self.member_ids),
            "state_anomaly_sample_count":
                self._state_anomaly.count,
            "increment_anomaly_sample_count":
                self._increment_anomaly.count,
            "state_anomaly_correlation":
                matrix_payload(
                    state_corr
                ),
            "increment_anomaly_correlation":
                matrix_payload(
                    increment_corr
                ),
            "state_anomaly_min_eigenvalue":
                min_eigenvalue(
                    state_corr
                ),
            "increment_anomaly_min_eigenvalue":
                min_eigenvalue(
                    increment_corr
                ),
            "note":
                (
                    "Capture mode does not modify model states. "
                    "Increment-anomaly correlation is the preferred "
                    "candidate process-noise ccorr diagnostic."
                ),
        }

        _atomic_json(
            self.capture_path,
            payload,
        )


    def _ensure_perturber(
        self,
        *,
        schema: tuple[
            tuple[str, int],
            ...
        ],
    ) -> LISGMAOStatePerturber:

        if self._perturber is not None:
            return self._perturber

        if (
            self._perturb_config
            is None
            or self._random_seed
            is None
        ):
            raise SACSMALISGMAORuntimeError(
                "perturbation configuration is incomplete."
            )

        perturber = LISGMAOStatePerturber(
            member_ids=self.member_ids,
            catchment_ids=tuple(
                catchment_id
                for catchment_id, _
                in schema
            ),
            config=self._perturb_config,
            random_seed=self._random_seed,
        )

        if self.restart_path.is_file():
            perturber.load_restart(
                self.restart_path
            )

        self._perturber = perturber

        return perturber


    @staticmethod
    def _materialize_requests(
        requests: Sequence[
            Mapping[str, Any]
        ],
        bounded_state: np.ndarray,
    ) -> tuple[dict[str, Any], ...]:

        result: list[
            dict[str, Any]
        ] = []

        for member_index, request in enumerate(
            requests
        ):

            copied_request = copy.deepcopy(
                dict(request)
            )

            raw_states = copied_request[
                "catchment_states"
            ]

            for catchment_index, raw in enumerate(
                raw_states
            ):

                for state_index, name in enumerate(
                    SACSMA_STATE_NAMES
                ):

                    raw[name] = float(
                        bounded_state[
                            state_index,
                            catchment_index,
                            member_index,
                        ]
                    )

            result.append(
                copied_request
            )

        return tuple(result)


    def apply_pf_ancestry(
        self,
        ancestors: Sequence[int],
        *,
        cycle_index: int,
    ) -> None:

        if self.mode != "perturb":
            return

        if self._perturber is None:
            raise SACSMALISGMAORuntimeError(
                "PF ancestry arrived before perturbation initialization."
            )

        values = np.asarray(
            ancestors,
            dtype=np.int64,
        )

        if values.shape != (
            len(self.member_ids),
        ):
            raise SACSMALISGMAORuntimeError(
                "PF perturbation ancestry size differs from ensemble."
            )

        identity = np.arange(
            len(self.member_ids),
            dtype=np.int64,
        )

        self._perturber.apply_ancestry(
            values
        )

        # Persist AFTER ancestry so restart resumes the correct particle lineage.
        self._perturber.save_restart(
            self.restart_path
        )

        path = (
            self.output_root
            / "perturbation_ancestry.jsonl"
        )

        payload = {
            "schema_version": 1,
            "cycle_index": int(cycle_index),
            "ancestors": [
                int(value)
                for value in values
            ],
            "nonidentity": bool(
                not np.array_equal(
                    values,
                    identity,
                )
            ),
            "unique_ancestor_count": int(
                np.unique(values).size
            ),
            "ar1_memory_follows_ancestry": True,
            "rng_streams_follow_ancestry": False,
        }

        with path.open(
            "a",
            encoding="utf-8",
        ) as stream:
            stream.write(
                json.dumps(
                    payload,
                    sort_keys=True,
                )
                + "\n"
            )

    def apply_pf_localized_ancestry(
        self,
        ancestry_by_catchment: Any,
        *,
        catchment_ids: Sequence[str],
        cycle_index: int,
    ) -> None:
        """Apply the coherent localized PF block to perturbation memory."""

        if self.mode != "perturb":
            return

        if self._perturber is None:
            raise SACSMALISGMAORuntimeError(
                "Localized PF ancestry arrived before "
                "perturbation initialization."
            )

        ids = tuple(
            str(value)
            for value in catchment_ids
        )

        if (
            not ids
            or len(set(ids)) != len(ids)
            or set(ids)
            != set(
                self.expected_catchment_ids
            )
        ):
            raise SACSMALISGMAORuntimeError(
                "Localized PF ancestry catchment "
                "domain differs."
            )

        values = np.asarray(
            ancestry_by_catchment,
            dtype=np.int64,
        )

        nmember = len(
            self.member_ids
        )

        if values.shape != (
            nmember,
            len(ids),
        ):
            raise SACSMALISGMAORuntimeError(
                "Localized PF perturbation ancestry "
                "has an invalid shape."
            )

        if (
            np.any(
                values < 0
            )
            or np.any(
                values >= nmember
            )
        ):
            raise SACSMALISGMAORuntimeError(
                "Localized PF perturbation ancestry "
                "contains an invalid member index."
            )

        identity = np.arange(
            nmember,
            dtype=np.int64,
        )

        nonidentity_columns = [
            column
            for column in range(
                values.shape[
                    1
                ]
            )
            if not np.array_equal(
                values[
                    :,
                    column,
                ],
                identity,
            )
        ]

        #
        # Enforce coherent-block ancestry: every affected catchment
        # must carry the same ancestry vector.
        #
        shared_ancestors = identity

        if nonidentity_columns:

            shared_ancestors = values[
                :,
                nonidentity_columns[
                    0
                ],
            ]

            for column in nonidentity_columns[
                1:
            ]:

                if not np.array_equal(
                    values[
                        :,
                        column,
                    ],
                    shared_ancestors,
                ):
                    raise SACSMALISGMAORuntimeError(
                        "Localized SAC-SMA ancestry is "
                        "not a coherent catchment block."
                    )

        self._perturber.apply_localized_ancestry(
            values,
            catchment_ids=ids,
        )

        self._perturber.save_restart(
            self.restart_path
        )

        path = (
            self.output_root
            / "perturbation_ancestry.jsonl"
        )

        payload = {
            "schema_version": 2,
            "cycle_index": int(
                cycle_index
            ),
            "localized": True,
            "catchment_count": len(
                ids
            ),
            "nonidentity_catchment_count": len(
                nonidentity_columns
            ),
            "shared_ancestors": [
                int(value)
                for value in shared_ancestors
            ],
            "coherent_catchment_block": True,
            "outside_support_identity": True,
            "ar1_memory_follows_ancestry": True,
            "rng_streams_follow_ancestry": False,
        }

        with path.open(
            "a",
            encoding="utf-8",
        ) as stream:

            stream.write(
                json.dumps(
                    payload,
                    sort_keys=True,
                )
                + "\n"
            )


    def apply_pf_multiblock_ancestry(
        self,
        ancestry_by_catchment: Any,
        *,
        catchment_ids: Sequence[str],
        block_ids: Sequence[str],
        cycle_index: int,
    ) -> None:
        """Apply coherent but potentially different ancestry by runoff block."""

        if self.mode != "perturb":
            return

        if self._perturber is None:
            raise SACSMALISGMAORuntimeError(
                "Multiblock PF ancestry arrived before "
                "perturbation initialization."
            )

        ids = tuple(
            str(value)
            for value
            in catchment_ids
        )

        if (
            not ids
            or len(set(ids)) != len(ids)
            or set(ids)
            != set(
                self.expected_catchment_ids
            )
        ):
            raise SACSMALISGMAORuntimeError(
                "Multiblock PF ancestry catchment "
                "domain differs."
            )

        blocks = tuple(
            str(value)
            for value
            in block_ids
        )

        if len(blocks) != len(ids):
            raise SACSMALISGMAORuntimeError(
                "Multiblock IDs do not align with "
                "the catchment domain."
            )

        values = np.asarray(
            ancestry_by_catchment,
            dtype=np.int64,
        )

        nmember = len(
            self.member_ids
        )

        if values.shape != (
            nmember,
            len(ids),
        ):
            raise SACSMALISGMAORuntimeError(
                "Multiblock PF ancestry has "
                "an invalid shape."
            )

        if (
            np.any(values < 0)
            or np.any(values >= nmember)
        ):
            raise SACSMALISGMAORuntimeError(
                "Multiblock PF ancestry contains "
                "an invalid member index."
            )

        identity = np.arange(
            nmember,
            dtype=np.int64,
        )

        outside_columns = [
            column
            for column, block
            in enumerate(blocks)
            if not block
        ]

        for column in outside_columns:

            if not np.array_equal(
                values[:, column],
                identity,
            ):
                raise SACSMALISGMAORuntimeError(
                    "Catchment outside configured "
                    "multigauge blocks is not identity."
                )

        ordered_blocks: list[str] = []

        for block in blocks:

            if (
                block
                and block not in ordered_blocks
            ):
                ordered_blocks.append(
                    block
                )

        block_payloads = []

        for block in ordered_blocks:

            columns = [
                column
                for column, current
                in enumerate(blocks)
                if current == block
            ]

            shared = np.asarray(
                values[
                    :,
                    columns[0],
                ],
                dtype=np.int64,
            )

            for column in columns[1:]:

                if not np.array_equal(
                    values[
                        :,
                        column,
                    ],
                    shared,
                ):
                    raise SACSMALISGMAORuntimeError(
                        "Catchments in the same multigauge block "
                        "do not share one coherent ancestry vector."
                    )

            block_payloads.append(
                {
                    "block_id": block,
                    "catchment_count": len(columns),
                    "nonidentity": bool(
                        not np.array_equal(
                            shared,
                            identity,
                        )
                    ),
                    "ancestors": [
                        int(value)
                        for value
                        in shared
                    ],
                }
            )

        self._perturber.apply_localized_ancestry(
            values,
            catchment_ids=ids,
        )

        self._perturber.save_restart(
            self.restart_path
        )

        path = (
            self.output_root
            / "perturbation_ancestry.jsonl"
        )

        payload = {
            "schema_version": 3,
            "cycle_index": int(
                cycle_index
            ),
            "localized": True,
            "multiblock": True,
            "catchment_count": len(ids),
            "block_count": len(
                ordered_blocks
            ),
            "outside_block_catchment_count": len(
                outside_columns
            ),
            "outside_support_identity": True,
            "coherent_within_each_block": True,
            "blocks": block_payloads,
            "ar1_memory_follows_ancestry": True,
            "rng_streams_follow_ancestry": False,
        }

        with path.open(
            "a",
            encoding="utf-8",
        ) as stream:

            stream.write(
                json.dumps(
                    payload,
                    sort_keys=True,
                )
                + "\n"
            )


    def _append_audit(
        self,
        *,
        cycle_index: int,
        analysis_epoch_seconds: int,
        result: Any,
    ) -> None:

        perturbation = np.asarray(
            result.perturbation,
            dtype=np.float64,
        )

        bounded_delta = (
            np.asarray(
                result.bounded_state,
                dtype=np.float64,
            )
            - np.asarray(
                result.raw_state,
                dtype=np.float64,
            )
        )

        payload = {
            "schema_version": 1,
            "cycle_index":
                int(cycle_index),
            "analysis_epoch_seconds":
                int(
                    analysis_epoch_seconds
                ),
            "state_order":
                list(
                    SACSMA_STATE_NAMES
                ),
            "raw_perturbation_mean_by_state": [
                float(value)
                for value in np.mean(
                    perturbation,
                    axis=(1, 2),
                )
            ],
            "raw_perturbation_std_by_state": [
                float(value)
                for value in np.std(
                    perturbation,
                    axis=(1, 2),
                )
            ],
            "bounded_delta_mean_by_state": [
                float(value)
                for value in np.mean(
                    bounded_delta,
                    axis=(1, 2),
                )
            ],
            "lower_bound_hit_count":
                int(
                    np.count_nonzero(
                        result.lower_bound_hits
                    )
                ),
            "upper_bound_hit_count":
                int(
                    np.count_nonzero(
                        result.upper_bound_hits
                    )
                ),
            "max_abs_standardized_perturbation":
                float(
                    np.max(
                        np.abs(
                            result
                            .truncated_standardized
                        )
                    )
                ),
            "v23_constraint_operator":
                "bounded_zero_sum_euclidean_projection",

            "projected_increment_std_by_state": [
                float(value)
                for value in np.std(
                    bounded_delta,
                    axis=(1, 2),
                )
            ],

            "max_abs_zero_sum_residual":
                float(
                    np.max(
                        np.abs(
                            np.sum(
                                bounded_delta,
                                axis=2,
                                dtype=np.float64,
                            )
                        )
                    )
                ),

            "max_abs_zero_mean_residual":
                float(
                    np.max(
                        np.abs(
                            np.mean(
                                bounded_delta,
                                axis=2,
                            )
                        )
                    )
                ),

            "projection_adjustment_rms_by_state": [
                float(value)
                for value in np.sqrt(
                    np.mean(
                        (
                            bounded_delta
                            - perturbation
                        )
                        ** 2,
                        axis=(1, 2),
                    )
                )
            ],

            "projection_changed_value_count":
                int(
                    np.count_nonzero(
                        np.abs(
                            bounded_delta
                            - perturbation
                        )
                        > 1.0e-12
                    )
                ),

        }

        self.audit_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        with self.audit_path.open(
            "a",
            encoding="utf-8",
        ) as stream:

            stream.write(
                json.dumps(
                    payload,
                    sort_keys=True,
                    allow_nan=False,
                )
                + "\n"
            )


    def prepare_requests(
        self,
        requests: Sequence[
            Mapping[str, Any]
        ],
        *,
        cycle_index: int,
        analysis_epoch_seconds: int,
        dt_seconds: float = 3600.0,
    ) -> tuple[
        Mapping[str, Any],
        ...
    ]:

        if self.mode == "off":
            return tuple(requests)

        (
            raw_state,
            schema,
            upper,
        ) = self._extract(
            requests
        )

        self._cycle_count += 1

        # Capture is always available in capture mode and intentionally
        # modifies no SAC-SMA state.
        if self.mode == "capture":

            self._capture(
                state=raw_state,
                upper=upper,
                schema=schema,
                cycle_index=cycle_index,
                analysis_epoch_seconds=(
                    analysis_epoch_seconds
                ),
            )

            return tuple(requests)

        if self.mode != "perturb":
            raise SACSMALISGMAORuntimeError(
                f"unsupported mode {self.mode!r}"
            )

        perturber = self._ensure_perturber(
            schema=schema
        )

        assert (
            self._std_fraction
            is not None
        )

        standard_deviation = (
            upper
            * self._std_fraction[
                :,
                None,
            ]
        )

        lower = np.zeros_like(
            upper
        )

        result = perturber.generate(
            state=raw_state,
            standard_deviation=(
                standard_deviation
            ),
            lower_bounds=lower,
            upper_bounds=upper,
            dt_seconds=float(
                dt_seconds
            ),
        )

        perturber.save_restart(
            self.restart_path
        )

        self._append_audit(
            cycle_index=cycle_index,
            analysis_epoch_seconds=(
                analysis_epoch_seconds
            ),
            result=result,
        )

        return self._materialize_requests(
            requests,
            result.bounded_state,
        )
