#!/usr/bin/env python3

"""
Write a local shell environment file for NextGenDA.

No secrets are written.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(
    __file__
).resolve().parents[1]


LOCK = (
    ROOT
    / "runtime"
    / "runtime-lock.json"
)


def main() -> int:

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--troute-source",
        type=Path,
        required=True,
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=(
            ROOT
            / ".nextgenda-runtime.env"
        ),
    )

    args = parser.parse_args()


    troute = (
        args.troute_source
        .expanduser()
        .resolve()
    )


    if not (
        troute
        / "src"
        / "bmi_troute.py"
    ).is_file():

        raise SystemExit(
            "ERROR: invalid t-route source directory: "
            f"{troute}"
        )


    lock = json.loads(
        LOCK.read_text(
            encoding="utf-8"
        )
    )


    image = lock[
        "production_container"
    ][
        "immutable_registry_reference"
    ]


    output = (
        args.output
        .expanduser()
        .resolve()
    )


    output.write_text(
        (
            "# Generated by NextGenDA.\n"
            "# Contains no credentials.\n\n"
            f'export NEXTGENDA_T_ROUTE_SOURCE="{troute}"\n'
            f'export NEXTGENDA_RUNTIME_IMAGE="{image}"\n'
        ),
        encoding="utf-8",
    )


    print(
        f"Wrote: {output}"
    )

    print()

    print(
        "Activate these values in the current shell with:"
    )

    print(
        f'source "{output}"'
    )


    return 0


if __name__ == "__main__":

    raise SystemExit(
        main()
    )
