#!/usr/bin/env python3

"""
Write local NextGenDA runtime configuration for Bash and PowerShell.

The generated files contain no credentials.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shlex


ROOT = (
    Path(__file__)
    .resolve()
    .parents[1]
)

LOCK = (
    ROOT
    / "runtime"
    / "runtime-lock.json"
)


def _powershell_quote(
    value: str,
) -> str:

    return (
        "'"
        + str(value).replace(
            "'",
            "''",
        )
        + "'"
    )


def main() -> int:

    parser = (
        argparse.ArgumentParser()
    )

    parser.add_argument(
        "--troute-source",
        type=Path,
        required=True,
    )

    parser.add_argument(
        "--output",
        type=Path,

        default=(
            ROOT
            / ".nextgenda-runtime.env"
        ),
    )

    parser.add_argument(
        "--powershell-output",
        type=Path,

        default=(
            ROOT
            / ".nextgenda-runtime.ps1"
        ),
    )

    args = parser.parse_args()

    troute = (
        args.troute_source
        .expanduser()
        .resolve()
    )

    if not (
        troute
        / "src"
        / "bmi_troute.py"
    ).is_file():

        raise SystemExit(
            "ERROR: invalid t-route source directory: "
            f"{troute}"
        )

    lock = json.loads(
        LOCK.read_text(
            encoding="utf-8"
        )
    )

    image = (
        lock[
            "production_container"
        ][
            "immutable_registry_reference"
        ]
    )

    bash_output = (
        args.output
        .expanduser()
        .resolve()
    )

    powershell_output = (
        args.powershell_output
        .expanduser()
        .resolve()
    )

    bash_output.write_text(
        (
            "# Generated by NextGenDA.\n"
            "# Contains no credentials.\n\n"
            "export NEXTGENDA_T_ROUTE_SOURCE="
            f"{shlex.quote(str(troute))}\n"
            "export NEXTGENDA_RUNTIME_IMAGE="
            f"{shlex.quote(str(image))}\n"
        ),
        encoding="utf-8",
    )

    powershell_output.write_text(
        (
            "# Generated by NextGenDA.\n"
            "# Contains no credentials.\n\n"
            "$env:NEXTGENDA_T_ROUTE_SOURCE = "
            f"{_powershell_quote(str(troute))}\n"
            "$env:NEXTGENDA_RUNTIME_IMAGE = "
            f"{_powershell_quote(str(image))}\n"
        ),
        encoding="utf-8",
    )

    print(
        f"Wrote Bash configuration: {bash_output}"
    )

    print(
        "Wrote PowerShell configuration: "
        f"{powershell_output}"
    )

    print()

    if os.name == "nt":

        print(
            "Optional PowerShell activation:"
        )

        print(
            f"  . {powershell_output}"
        )

    else:

        print(
            "Optional Bash activation:"
        )

        print(
            f'  source "{bash_output}"'
        )

    print()

    print(
        "The standard bootstrap installation does not "
        "require manual activation when using the "
        "default NextGenDA runtime locations."
    )

    return 0


if __name__ == "__main__":

    raise SystemExit(
        main()
    )
